name: aroundix_design
description:  apps theme.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  reactive_forms: ^14.1.0
  reactive_phone_form_field: ^0.9.0
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1

  extended_image: ^6.0.2+1
  intl_phone_field: ^3.1.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_screenutil: ^5.4.0
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  aroundix_core:
    path: ../aroundix_core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4




flutter:
  fonts:
    - family: PIcons
      fonts:
        - asset: lib/src/fonts/PIcons.ttf
    - family: NotoKufiArabic
      fonts:
        - asset: lib/src/fonts/ar/NotoKufiArabic-Black.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Bold.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-ExtraBold.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-ExtraLight.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Light.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Medium.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Regular.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-SemiBold.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Thin.ttf
    - family: NotoSans
      fonts:
        - asset: lib/src/fonts/en/NotoSans-Black.ttf
        - asset: lib/src/fonts/en/NotoSans-BlackItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-Bold.ttf
        - asset: lib/src/fonts/en/NotoSans-BoldItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-ExtraBold.ttf
        - asset: lib/src/fonts/en/NotoSans-ExtraBoldItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-ExtraLight.ttf
        - asset: lib/src/fonts/en/NotoSans-ExtraLightItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-Italic.ttf
        - asset: lib/src/fonts/en/NotoSans-Light.ttf
        - asset: lib/src/fonts/en/NotoSans-LightItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-Medium.ttf
        - asset: lib/src/fonts/en/NotoSans-MediumItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-Regular.ttf
        - asset: lib/src/fonts/en/NotoSans-SemiBold.ttf
        - asset: lib/src/fonts/en/NotoSans-SemiBoldItalic.ttf
        - asset: lib/src/fonts/en/NotoSans-Thin.ttf
        - asset: lib/src/fonts/en/NotoSans-ThinItalic.ttf
