name: aroundix_network
description: e-commerce networking utils.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
#  refresh_bot:
#    git:
#      url: git@github.com:flutterbots/flutterbots.git
#      path: packages/refresh_bot



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  freezed: ^2.0.3+1